version: '3.8'

services:
  reverse-proxy:
    build: ./nginx
    container_name: reverse_proxy
    ports:
      - "80:80"
    depends_on:
      - java-app
      - node-app

  java-app:
    build: ./java-app
    container_name: java_app
    expose:
      - "8080"

  node-app:
    build: ./node-app
    container_name: node_app
    expose:
      - "3000"
